test:
  - test/**/*

module/feature:
  - feature_book/**/*
  - feature_book_details/**/*
  - feature_audiobook_enhance_details/**/*

module/player:
  - feature_mini_player/**/*
  - feature_playerfullscreen/**/*

library/downloader:
  - feature_downloader/**/*

module/library:
  - common/**/*
  - buildSrc/**/*
  - services/**/*
  - database/**/*

module/app:
  - app/**/*

app:
  -./*