- regExp: ".*\\.kt+$"
  labels: ["code","kotlin"]
- regExp: ".*\\.yml+$"
  labels: ["CI", "critical"]
- regExp: ".*\\.md+$"
  labels: ["documentation"]
- regExp: ".*\\.png+$"
  labels: ["images"]
- regExp: "^(pom\\.xml|package\\.json|build\\.gradle)$"
  labels: ["dependencies"]
- regExp: ".*\\.(zip|jar|war|ear)+$"
  labels: ["artifact", "invalid"]