name: AudioBook Dependency Graph

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release*'

jobs:
  dependencyGraphJob:
    name: Build dependency Graph for modules
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install dependencies before generating Graph
        run: apt-get install graphviz

      - name: Generate Graph
        run: bash ./gradlew :app:projectDependencyGraph


  apk:
    name: Save to Git Repository
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Path of stored
        run: cd ./build/reports/ && ls